-- Insertar información en la base de datos

USE colectivos_pna;

-- id: 1
-- nombre: Línea 1
-- trayecto_colectivo_ida_id: 1
INSERT INTO `paradas` (ubicacion) VALUES
("Alfonsina Storni - Quinquela Martin"),
("Gdor. Lopez Jordan - Francia"),
("Gdor. Lopez Jordan - Prof. Franciso C. Garcilazo"),
("Gdor. Lopez Jordan - Rio Gualeguay"),
("Rio Gualeguay - El Temple Argentino"),
("Celia Torra - Calle 1310"),
("Celia Torra - Francia"),
("Celia Torra - Cesario Quiros"),
("Celia Torra - Israel Hoffman"),
("Israel Hoffman - Andres Longo"),
("Israel Hoffman - Gdor. Manuel Crespo"),
("Av. Churruarin - Dr. Rene Favaloro"),
("Av. Churruarin - Facundo Quiroga"),
("Av. Churruarin - Calle 1202"),
("Blas Parera - Salustiano Zavalia"),
("Rio Negro - Salustiano Zavalia"),
("Rio Negro - Av. Churruarin"),
("Av. Churruarin - Gaspar Benaven"),
("Av. Churruarin - Pedro Vargas"),
("Av. Churruarin - Diaz Velez"),
("Av. Churruarin - Ayacucho"),
("Av. Churruarin - Grella"),
("Av. Churruarin - Juan Gorriti"),
("3 de Febrero - Colodredo"),
("Av. Almafuerte - Esteban Rams"),
("Av. Almafuerte - Av. Churruarin"),
("Gualeguaychu - Cura Alvarez"),
("Gualeguaychu - Pascual Palma"),
("Gualeguaychú - Arturo Illia"),
("Gualeguaychú - 9 de Julio"),
("Ernesto Bavio - Chile"),
("Italia - Perú"),
("Santa Fe - 25 de Junio"),
("Santa Fe - de la Puente"),
("Santa Fe - Garay"),
("Santa Fe - Malvinas"),
("Malvinas - Gral. Jose de San Martin"),
("San Lorenzo - San Juan"),
("Salta - Blvd. Mariano Moreno"),
("Martín Miguel de Güemes - Av. Laurencena"),
("Av. Laurencena - Rioja"),
("Av. Laurencena - Evaristo Carriego"),
("Av. Francisco Ramirez - Félix de Azara"),
("Av. Francisco Ramirez - Juan Ambrosetti"),
("Av. Francisco Ramirez - Alfredo Du Gratty"),
("Augusto Bravard - Francisco Soler"),
("Francisco Soler - Alfredo Du Gratty"),
("Francisco Soler - Juan Ambrosetti"),
("Juan Ambrosetti - Club Ministerio"),
("Juan Ambrosetti - Raul Patricio Solanas"),
("Juan Ambrosetti - Ayacucho"),
("Juan Ambrosetti - Rondeau"),
("Juan Ambrosetti - Dr. Quinodoz"),
("Juan Ambrosetti - Blas Parera"),
("Blas Parera - Carlos Darwin"),
("Blas Parera - Esteban Echeverria"),
("Blas Parera - Ingeniero Jm. Jozami"),
("Ingeniero Jm. Jozami - Rondeau");

-- id: 1
-- nombre: Línea 1
-- trayecto_colectivo_vuelta_id: 3
INSERT INTO `paradas` (ubicacion) VALUES
("Ingeniero Jm. Jozami - Rondeau"),
("Rondeau Ñandú"),
("Rondeau - Esteban Echeverria"),
("Rondeau - Dr. Juan Carlos Anzola"),
("Carlos Darwin - Dr. Juan Carlos Anzola"),
("Carlos Darwin - Blas Parera"),
("Blas Parera - Juan Ambrosetti"),
("Blas Parera - Antonio Crespo"),
("Blas Parera - Martin Fierro"),
("Av. Circunvalacion Jose Hernandez - Esc. de Polici"),
("Av. Circunvalacion Jose Hernandez - Rondeau"),
("Juan Ambrosetti - Rondeau"),
("Juan Ambrosetti - Estadio de Softball"),
("Juan Ambrosetti - Camping Pucara"),
("Juan Ambrosetti - Club Ministerio"),
("Juan Ambrosetti - Francisco Soler"),
("Francisco Soler - Alfredo Du Gratty"),
("Alfredo Du Gratty - Av. Francisco Ramirez"),
("Av. Francisco Ramirez - Martin de Moussy"),
("Av. Francisco Ramirez - Manuel Leiva"),
("Av. Laurencena - Simon Bolivar"),
("Av. Laurencena - Manuel Dorrego"),
("Martin Miguel de Güemes - Altura 1000"),
("Martin Miguel de Güemes - Av. Mariano Moreno"),
("Av. Mariano Moreno - de la Torre Y Vera"),
("Av. Mariano Moreno - Gral. Jose de San Martin"),
("Av. Bartolome Mitre - Santa Fe"),
("Cordoba - Malvinas"),
("Cordoba - Plaza Carbo"),
("Cordoba - Cervantes"),
("Cordoba - 25 de Junio"),
("España - Italia"),
("25 de Mayo - 9 de Julio"),
("25 de Mayo - Arturo Illia"),
("Gral. Pascual Echagüe - Pascual Palma"),
("Gral. Pascual Echagüe - Cura Alvarez"),
("Av. Churruarin - Fray Mamerto Esquiu"),
("Av. Churruarin - 3 de Febrero"),
("Av. Churruarin - Sargento Cabral"),
("Av. Churruarin - Ayacucho"),
("Av. Churruarin - Santiago Derqui"),
("Av. Churruarin - Pedro Vargas"),
("Av. Churruarin - Dr. Fransico Perette"),
("Av. Churruarin - Rio Negro"),
("Rio Negro - Zuviria"),
("Regis Martinez - Blas Parera"),
("Blas Parera - Salustiano Zavalia"),
("Av. Churruarin - Ricardo Guiraldes"),
("Av. Churruarin - Facundo Quiroga"),
("Gdor. Manuel Crespo - Ricardo Guiraldes"),
("Israel Hoffman - Andres Longo"),
("Israel Hoffman - Celia Torra"),
("Celia Torra - Francia"),
("Celia Torra - Calle 1303"),
("Rio Gualeguay - El Temple Argentino"),
("Rio Gualeguay - Gdor. Lopez Jordan"),
("Gdor. Lopez Jordan - Dr. Francisco C. Garcilazo"),
("Gdor. Lopez Jordan - Francia"),
("Gdor. Lopez Jordan - Lola Mora"),
("Alfonsina Storni - Quinquela Martin");

-- Lo anterior se corresponde con la inserción de las paradas de ida y vuelta de la Línea 1, aunque solo con el trayecto id 1 y 3.
